apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-gitops
  name: hello-gitops
spec:
  ports:
  - name: "80"
    nodePort: 30400
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-gitops
  type: NodePort
status:
  loadBalancer: {}
